services:
  - type: web
    name: webhook-receiver
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: WEBHOOK_SECRET
        sync: false

